
title: Ragip Volkan Tatlikazan
logo: /assets/logo/PictureBW-small.png
description: "Here you can see my projects on \n Natural Language Processing \n & Adv. Driver Assistance Systems"
#show_downloads:
theme: jekyll-theme-minimal