
title: Ragip Volkan Tatlikazan
logo: /assets/logo/PictureBW-small.png
description: "Here you can see my projects on

  Natural Language Processing &

  Adv. Driver Assistance Systems"
#show_downloads:
theme: jekyll-theme-minimal

#https://github.com/DCgov/guides-template/blob/gh-pages/_config.yml